-- =====================================================
-- VERIFICAR TABLAS EXISTENTES EN ORACLE
-- Usuario: otito
-- =====================================================

SET LINESIZE 200
SET PAGESIZE 1000
COLUMN TABLE_NAME FORMAT A30
COLUMN NUM_ROWS FORMAT 999999
COLUMN LAST_ANALYZED FORMAT A20

-- 1. LISTAR TODAS LAS TABLAS DEL USUARIO
SELECT 
    TABLE_NAME,
    NUM_ROWS,
    TO_CHAR(LAST_ANALYZED, 'DD/MM/YYYY HH24:MI') as LAST_ANALYZED
FROM USER_TABLES
ORDER BY TABLE_NAME;

-- 2. VERIFICAR ESPECÍFICAMENTE LAS TABLAS QUE NECESITAMOS
SELECT 'TABLA_ORACLE' as TIPO, TABLE_NAME, NUM_ROWS
FROM USER_TABLES
WHERE TABLE_NAME IN (
    -- Tablas esperadas en Oracle según script original
    'SEG_USUARIOS',
    'SEG_ROLES', 
    'SEG_AREAS',
    'HD_TICKETS',
    'HD_TICKET_HISTORIAL',
    'ESTADOS_TICKET',
    'PRIORIDADES',
    'CATEGORIAS',
    'HD_CATEGORIAS',
    'ACT_INVENTARIO',
    'ACT_TIPOS_ACTIVO',
    -- Tablas que las entidades C# esperan
    'INV_ACTIVOS',
    'GLPI_TICKETS_DETALLE'
)
ORDER BY TABLE_NAME;

-- 3. VERIFICAR TABLAS QUE EMPIEZAN CON PREFIJOS CONOCIDOS
SELECT 'PREFIJO_SEG' as GRUPO, TABLE_NAME, NUM_ROWS 
FROM USER_TABLES 
WHERE TABLE_NAME LIKE 'SEG_%'
UNION ALL
SELECT 'PREFIJO_HD' as GRUPO, TABLE_NAME, NUM_ROWS 
FROM USER_TABLES 
WHERE TABLE_NAME LIKE 'HD_%'
UNION ALL
SELECT 'PREFIJO_ACT' as GRUPO, TABLE_NAME, NUM_ROWS 
FROM USER_TABLES 
WHERE TABLE_NAME LIKE 'ACT_%'
UNION ALL
SELECT 'PREFIJO_INV' as GRUPO, TABLE_NAME, NUM_ROWS 
FROM USER_TABLES 
WHERE TABLE_NAME LIKE 'INV_%'
UNION ALL
SELECT 'PREFIJO_GLPI' as GRUPO, TABLE_NAME, NUM_ROWS 
FROM USER_TABLES 
WHERE TABLE_NAME LIKE 'GLPI_%'
ORDER BY GRUPO, TABLE_NAME;

-- 4. CONTAR TABLAS POR PREFIJO
SELECT 
    SUBSTR(TABLE_NAME, 1, INSTR(TABLE_NAME || '_', '_') - 1) as PREFIJO,
    COUNT(*) as CANTIDAD
FROM USER_TABLES
GROUP BY SUBSTR(TABLE_NAME, 1, INSTR(TABLE_NAME || '_', '_') - 1)
ORDER BY CANTIDAD DESC;
