-- =====================================================
-- SCRIPT DE VERIFICACIÓN DE BASE DE DATOS ORACLE
-- Sistema ITSM
-- =====================================================

-- 1. VERIFICAR USUARIO ACTUAL Y PERMISOS
SELECT 'Usuario Actual' as TIPO, USER as VALOR FROM DUAL;
SELECT 'Esquema Actual' as TIPO, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') as VALOR FROM DUAL;

-- 2. VERIFICAR PERMISOS DEL USUARIO
SELECT 
    'PERMISO' as TIPO,
    PRIVILEGE as VALOR
FROM USER_SYS_PRIVS
WHERE PRIVILEGE IN ('CREATE SESSION', 'CREATE TABLE', 'CREATE SEQUENCE', 
                     'CREATE TRIGGER', 'CREATE PROCEDURE', 'SELECT ANY TABLE')
UNION ALL
SELECT 
    'ROLE' as TIPO,
    GRANTED_ROLE as VALOR
FROM USER_ROLE_PRIVS;

-- 3. VERIFICAR TABLAS REQUERIDAS
SELECT 
    'TABLA_EXISTE' as ESTADO,
    TABLE_NAME,
    NUM_ROWS,
    LAST_ANALYZED
FROM USER_TABLES
WHERE TABLE_NAME IN (
    'SEG_USUARIOS',
    'SEG_ROLES', 
    'SEG_AREAS',
    'HD_TICKETS',
    'HD_CATEGORIAS',
    'ESTADOS_TICKET',
    'PRIORIDADES',
    'CATEGORIAS',
    'ACT_INVENTARIO',
    'ACT_TIPOS_ACTIVO'
)
ORDER BY TABLE_NAME;

-- 4. VERIFICAR TABLAS FALTANTES
SELECT 
    'TABLA_FALTANTE' as ESTADO,
    COLUMN_VALUE as TABLE_NAME,
    NULL as NUM_ROWS,
    NULL as LAST_ANALYZED
FROM TABLE(SYS.ODCIVARCHAR2LIST(
    'SEG_USUARIOS', 'SEG_ROLES', 'SEG_AREAS',
    'HD_TICKETS', 'HD_CATEGORIAS', 'ESTADOS_TICKET',
    'PRIORIDADES', 'CATEGORIAS', 
    'ACT_INVENTARIO', 'ACT_TIPOS_ACTIVO'
))
WHERE COLUMN_VALUE NOT IN (
    SELECT TABLE_NAME FROM USER_TABLES
);

-- 5. VERIFICAR SECUENCIAS
SELECT 
    'SECUENCIA' as TIPO,
    SEQUENCE_NAME as NOMBRE,
    LAST_NUMBER as ULTIMO_VALOR
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME LIKE 'SEQ_%' OR SEQUENCE_NAME LIKE '%_SEQ';

-- 6. VERIFICAR TRIGGERS
SELECT 
    'TRIGGER' as TIPO,
    TRIGGER_NAME as NOMBRE,
    STATUS,
    TABLE_NAME
FROM USER_TRIGGERS
WHERE TRIGGER_NAME IN ('TRG_ASIGNAR_CODIGO_TICKET', 'TRG_CALCULAR_PRIORIDAD');

-- 7. VERIFICAR FUNCIONES
SELECT 
    'FUNCTION' as TIPO,
    OBJECT_NAME as NOMBRE,
    STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'FUNCTION'
AND OBJECT_NAME = 'FN_OBTENER_SIGUIENTE_CODIGO_TICKET';

-- 8. VERIFICAR DATOS INICIALES
SELECT 'DATOS_SEG_ROLES' as TABLA, COUNT(*) as REGISTROS FROM SEG_ROLES;
SELECT 'DATOS_SEG_AREAS' as TABLA, COUNT(*) as REGISTROS FROM SEG_AREAS;
SELECT 'DATOS_ESTADOS_TICKET' as TABLA, COUNT(*) as REGISTROS FROM ESTADOS_TICKET;
SELECT 'DATOS_PRIORIDADES' as TABLA, COUNT(*) as REGISTROS FROM PRIORIDADES;
SELECT 'DATOS_CATEGORIAS' as TABLA, COUNT(*) as REGISTROS FROM CATEGORIAS;
SELECT 'DATOS_HD_CATEGORIAS' as TABLA, COUNT(*) as REGISTROS FROM HD_CATEGORIAS;
SELECT 'DATOS_ACT_TIPOS_ACTIVO' as TABLA, COUNT(*) as REGISTROS FROM ACT_TIPOS_ACTIVO;

-- 9. VERIFICAR ÍNDICES CRÍTICOS
SELECT 
    'INDICE' as TIPO,
    INDEX_NAME,
    TABLE_NAME,
    UNIQUENESS
FROM USER_INDEXES
WHERE TABLE_NAME IN ('HD_TICKETS', 'SEG_USUARIOS')
ORDER BY TABLE_NAME, INDEX_NAME;

-- 10. VERIFICAR CONSTRAINTS
SELECT 
    'CONSTRAINT' as TIPO,
    CONSTRAINT_NAME,
    TABLE_NAME,
    CONSTRAINT_TYPE,
    STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('SEG_USUARIOS', 'HD_TICKETS', 'ESTADOS_TICKET')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

-- 11. PROBAR CONECTIVIDAD Y OPERACIONES BÁSICAS
SELECT 'TEST_SELECT' as OPERACION, COUNT(*) as RESULTADO FROM SEG_USUARIOS;
SELECT 'TEST_SYSDATE' as OPERACION, TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') as RESULTADO FROM DUAL;

-- 12. RESUMEN DE VALIDACIÓN
SELECT 
    'RESUMEN' as SECCION,
    (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME LIKE 'SEG_%' OR TABLE_NAME LIKE 'HD_%' OR TABLE_NAME LIKE 'ACT_%') as TABLAS_CREADAS,
    (SELECT COUNT(*) FROM USER_SEQUENCES) as SECUENCIAS,
    (SELECT COUNT(*) FROM USER_TRIGGERS WHERE STATUS = 'ENABLED') as TRIGGERS_ACTIVOS,
    (SELECT COUNT(*) FROM SEG_USUARIOS) as USUARIOS_REGISTRADOS
FROM DUAL;
